# if encoding parts are empty, source data are seen as already encoded
# used to infer an activity description
[encoding.activity]
1 = "Imputed personal or household care"
2 = "Sleep and naps"
3 = "Imputed sleep"
4 = "Wash, dress, care for self"
5 = "Meals at work or school"
6 = "Meals or snacks in other places"
8 = "Paid work at home"
10 = "Unpaid work to generate household income"
12 = "Work breaks"
13 = "Other time at workplace"
14 = "Look for work"
15 = "Regular schooling, education"
16 = "Homework"
17 = "Leisure and  other education or training"
18 = "Food preparation, cooking"
19 = "Set table, wash/put away dishes"
20 = "Cleaning"
21 = "Laundry, ironing, clothing repair"
22 = "Maintain home/vehicle, including collect fuel"
23 = "Other domestic work"
25 = "Consume personal care services"
26 = "Consume other services"
27 = "Pet care (not walk dog)"
28 = "Physical, medical child care"
29 = "Teach, help with homework"
30 = "Read to, talk or play with child"
31 = "Supervise, accompany, other child care"
32 = "Adult care"
46 = "Gardening/pick mushrooms"
49 = "Conversation (in person, phone)"
50 = "Games (social and  solitary)/other in-home social"
51 = "General indoor leisure"
52 = "Art or music"
53 = "Correspondence (not e-mail)"
54 = "Knit, crafts or hobbies"
55 = "Relax, think, do nothing"
56 = "Read"
57 = "Listen to music or other audio content"
58 = "Listen to radio"
59 = "Watch tv, video, dvd, streamed film"
60 = "Computer games"
61 = "E-mail, surf internet, computing"
7 = "Paid work-main job (not at home)"
9 = "Second or other job not at home"
24 = "Purchase goods"
33 = "Voluntary, civic, organisational act"
34 = "Worship and religion"
35 = "General out-of-home leisure"
36 = "Attend sporting event"
37 = "Cinema, theatre, opera, concert"
38 = "Other public event, venue"
39 = "Restaurant, cafe, bar, pub"
40 = "Party, social event, gambling"
48 = "Receive or visit friends"
41 = "Imputed time away from home"
42 = "General sport or exercise"
45 = "Other outside recreation"
62 = "No activity, imputed or recorded transport"
69 = "No recorded activity"
99 = "Missing"

# used to infer an activity description
[encoding.travel_modes]
43 = "Walking"
44 = "Cycling"
11 = "Travel as a part of work"
47 = "Walk dogs"
63 = "Travel to/from work"
64 = "Education travel"
65 = "Voluntary/civic/religious travel"
66 = "Child/adult care travel"
67 = "Shop, person/hhld care travel"
68 = "Other travel"

# decoding defines the string representations for encoded elements (-> relevant for embedding similarity and thus subject to tuning)
[decoding.activity]
1 = "What is a typical place to conduct daily self-care activities or domestic care? Can also be at home apartment, detached house or building."
2 = "What is a residential accomodation (at apartment, detached house or building) for sleeping?"
3 = "What is a residential accomodation (at apartment, detached house or building) for sleeping?"
4 = "Where can someone do personal hygiene, showering and dressing?"
5 = "Where are meals at work or school usually eaten?"
6 = "Where can I get a meal or take snacks?"
7 = "Workplace for working full time like offices or shops."
8 = "Working at home or at a personal accommodation"
9 = "Workplace for working in a second job like offices or shops"
10 = "Where is unpaid work to generate household income usually conducted"
11 = "Travel as a part of work"
12 = "Where do work breaks usually take place?"
13 = "Being at the workplace"
14 = "Being on job search?"
15 = "Regular schooling, education"
16 = "Where to do Homework?"
17 = "Where to spend leisure time, educate yourself or train?"
18 = "What is a usual place for personal cooking and food preparation? (Often at apartment, detached house or building)"
19 = "At residential home/apartment/accomodation/house/building, set the table, do kitchen utensil cleaning or do dining room work."
20 = "Doing domestic work. Residential House/apartment/accommodation cleanup."
21 = "Where are laundry, ironing, and clothing repair usually done?"
22 = "Where to maintain or repair home/vehicle or collect fuel?"
23 = "Where is domestic work usually conducted?"
24 = "Where are goods and food typically purchased?"
25 = "Where can one use personal care services?"
26 = "Where can one use other services?"
27 = "Where is pet care (excluding dog walking) usually performed?"
28 = "Where is physical or medical child care typically provided?"
29 = "Where can one teach or help children with homework?"
30 = "Where is a good place to read to, talk to, or play with a child?"
31 = "Where can one supervise, accompany, or provide other child care?"
32 = "Where is adult care usually provided?"
33 = "Where can one take part in voluntary, civic, or organizational activities?"
34 = "Places for worship and religious activities"
35 = "Where can one spend leisure time outside home?"
36 = "Where can one attend a sporting event?"
37 = "Cinema, theatre, opera, concert"
38 = "Where can one attend other public events or venues?"
39 = "Visit or eat at restaurant, cafe, bar or pub"
40 = "Where can one party or engage in social events or gambling?"
41 = "Spending time away from home"
42 = "Where can one exercise or do general sports?"
43 = "Walking"
44 = "Cycling"
45 = "Places for outside recreation"
46 = "Where to do gardening or pick mushrooms?"
47 = "Where to walk dogs?"
48 = "Where are friends typically visited or received?"
49 = "Places for in person or phone conversations"
50 = "Where can one play games (social or solitary) or engage in other in-home social activities?"
51 = "Places for indoor leisure"
52 = "Where can one engage in art or music?"
53 = "Where is postal correspondence usually written?"
54 = "Where can one do knitting, crafts, or similar hobbies?"
55 = "Place to relax, think or do nothing"
56 = "Where is a good place to read?"
57 = "Where can one listen to music or other audio content?"
58 = "Where can one listen to the radio?"
59 = "Where is a suitable place to watch TV, video, DVD, or streamed film?"
60 = "Places to play computer games"
61 = "Place for doing E-mails, internet surfing or other computer related activities?"
62 = "other transport"
63 = "Travel to/from work"
64 = "Education travel"
65 = "Voluntary/civic/religious travel"
66 = "Child/adult care travel"
67 = "Shop, personal or household care travel"
68 = "Other travel"
69 = "Doing nothing or waiting"
70 = "doing something"


[decoding.travel_modes]
43 = "walk"
44 = "bicycle"
106 = "drive"
101 = "drive"
102 = "drive"
103 = "walking"
104 = "physical mobility"
105 = "mobility"

# used to infer a travel mode, compared with MAIN attribute in MTUS
[properties.travel_activities]
11 = "Travel as a part of work"
43 = "Walking"
44 = "Cycling"
62 = "other transport"
63 = "Travel to/from work"
64 = "Education travel"
65 = "Voluntary/civic/religious travel"
66 = "Child/adult care travel"
67 = "Shop, personal or household care travel"
68 = "travel"

# not closer specified travel activities (in this case travel activities are preferred for more accurate transport information)
# used to infer a travel mode, compared with MTRAV attribute in MTUS
[properties.unspecified_travel]
104 = "Other physical transport"
105 = "Other/unspecified transport"

# activities/modes terminating an agenda (e.g. flying to a not simulated area)
[properties.endpoints]