[building.Accommodation]
apartments = "Residential apartment or flat. A building containing separate residential apartments."
barracks = "Buildings built to house military personnel or laborers."
bungalow = "A single-storey detached small house, Dacha."
cabin = "A cabin is a small, roughly built house usually with a wood exterior and typically found in rural areas."
detached = "A detached house, a free-standing residential building usually housing a single family."
dormitory = "A shared building intended for college/university students."
farm = "A residential building on a farm (farmhouse)."
ger = "A round yurt or ger."
hotel = "A building with rooms available for overnight accommodation."
house = "A home inhabited by a single household (a family or small group with shared kitchen, bathrooms and living areas)."
houseboat = "A boat used as a home"
residential = "A building used for residential purposes."
semidetached_house = "A pair of residences joined into one building by a common sidewall. (duplex)"
static_caravan = "A mobile home left on a single site"
stilt_house = "A residential house raised on piles over the surface of the soil or a body of water"
terrace = "a group of residential row houses."
tree_house = "Small hut, sometimes also as a room or small apartment. Built on tree posts or on a natural tree."
trullo = "A stone hut with a conical roof."

[building.Commercial]
commercial = "A building for commercial activities."
industrial = "A building for industrial purposes."
kiosk = "A small one-room retail building."
office = "An office building."
retail = "A building used for selling goods to the public."
supermarket = "A self-service retail market selling especially foods and household merchandise"
warehouse = "A building for the storage of goods or as part of a distribution system."

[building.Religious]
religious = "Building related to religion."
cathedral = "Cathedral."
chapel = "Chapel."
church = "Church."
kingdom_hall = "Kingdom Hall."
monastery = "Monastery. Often, monasteries consist of several specialized buildings."
mosque = "Mosque."
presbytery = "A building where priests live and work. Often, part of a church reserved for the officiating clergy"
shrine = "Shrine."
synagogue = "Synagogue."
temple = "Temple."

[building.Civic_or_amenity]
bakehouse = "Bakehouse (i.e. for baking bread)."
bridge = "Bridge (skyway)."
civic = "A building housing some civic amenity (e.g. a community centre, a library, toilets, a sports centre, swimming pools or a townhall etc.)"
college = "College."
fire_station = "Fire station, i.e. to house fire fighting equipment and officers."
government = "Government building (municipal, provincial or divisional secretaries, government agencies or departments, town halls, parliaments or court houses)"
gatehouse = "An entry control point, spanning over a highway that enters a city or compound."
hospital = "Hospital."
kindergarten = "kindergarten for children usually from five to six years old."
museum = "Museum."
public = "A building accessible to the general public (a town hall, police station, court house, etc.)."
school = "School."
toilets = "A toilet block."
train_station = "Train station building."
transportation = "Public transport building."
university = "A university building."

[building.Agricultural_or_plant_production]
barn = "An agricultural building used for storage and as a covered workplace."
conservatory = "Indoor garden or a sunroom (winter garden)."
cowshed = "A cowshed (cow barn, cow house) housing cows, usually found on farms."
farm_auxiliary = "A building on a farm."
greenhouse = "Building used to grow plants."
slurry_tank = "A manure tank hold animal excreta (also known as slurry)."
stable = "Stable for horses."
sty = "A sty (pigsty, pig ark, pig-shed) for raising domestic pigs, usually found on farms."
livestock = "A building housing/raising livestock."

[building.Sports]
grandstand = "The main stand for spectators at racecourses or sports grounds."
pavilion = "A sports pavilion with changing rooms, storage areas and possibly a space for functions & events."
riding_hall = "Riding hall."
sports_hall = "Sports hall."
sports_centre = "Sports centre."
stadium = "Stadium building."

[building.Storage]
allotment_house = "A small outbuilding in an allotment garden."
boathouse = "Building for the storage of boats."
hangar = "Building for the storage of airplanes, helicopters or space-craft."
hut = "A hut is a small and crude shelter."
shed = "Shed in a back garden or on an allotment used for storage, hobbies, or as a workshop."

[building.Cars]
carport = "A Carport offers protection to vehicles, primarily cars, from the elements."
garage = "A shelter or repair shop for automotive vehicles."
garages = "A building containing discrete parking/storage spaces."
parking = "Structure for parking cars."

[building.Power_or_technical_buildings]
digester = "Bioreactor for the production of biogas from biomass."
service = "Small unmanned building with certain machinery (like pumps or transformers)."
tech_cab = "Small prefabricated cabin structures for the air-conditioned accommodation of different technology."
transformer_tower = "A transformer tower is a characteristic tall building comprising a distribution transformer and constructed to connect directly to a medium voltage overhead power line. Quite often the power line has since been undergrounded but the building may still serve as a substation. If the building is still in use as a substation it should additionally be tagged as power=substation + substation=minor_distribution."
water_tower = "A water tower."
storage_tank = "Storage tanks are containers that hold liquids"
silo = "A silo is a building for storing bulk materials"

[building.other]
beach_hut = "A small cabin or shelter on popular bathing beaches."
bunker = "A hardened military building."
castle = "Castle."
construction = "Building under construction."
container = "Container used as a permanent building."
guardhouse = "A small building to house guard(s)."
military = "A military building."
outbuilding = "A building near to a larger building."
pagoda = "Pagoda."
quonset_hut = "A lightweight prefabricated structure in the shape of a semicircle."
roof = "A roof with open sides, such as a rain shelter, and also gas stations"
ruins = "Building that is abandoned and in poor condition."
tent = "Permanently placed tent."
tower = "A tower-building."
windmill = "A traditional windmill, historically used to mill grain with wind power."
yes = "building"
