[leisure]
adult_gaming_centre = "A venue with gambling machines and other pay-to-play games."
amusement_arcade = "A venue with pay-to-play games, such as video games, driving simulators, pinball machines, merchandisers, etc."
bandstand = "An open structure where musical bands can perform concerts."
bathing_place = "Public place where you can freely bath in nature."
beach_resort = "A managed beach."
bird_hide = "A place to observe birds."
bleachers = "Raised, tiered rows of benches at spectator events"
bowling_alley = "A facility that is equipped to play the game of bowling."
common = "A common land."
dance = "A place to go dancing."
disc_golf_course = "Disc golf course"
dog_park = "Designated area, where dog-owners are permitted to exercise their pets unrestrained."
escape_game = "A physical adventure game in which players solve a series of puzzles using clues, hints and strategy to complete the objectives at hand."
firepit = "A permanent location or structure to host campfires, bonfires, etc."
fishing = "A place for fishing."
fitness_centre = "A place with exercise machines and/or fitness/dance classes."
fitness_station = "A place with exercise machines, outdoor."
garden = "outside greenery where flowers and other plants are grown in a decorative manner or for scientific purposes."
golf_course = "A golf course."
hackerspace = "A place where people with common interests, often in computers, technology, science, digital art or electronic art, can meet, socialize and/or collaborate."
horse_riding = "A facility where people practise horse riding, usually in their spare time, e.g. a riding centre."
ice_rink = "A place where you can skate or play ice hockey."
marina = "For mooring leisure yachts and motor boats."
miniature_golf = "A place or area that you can play miniature golf."
nature_reserve = "Protected area of importance for wildlife, flora, fauna or features of geological or other special interest."
outdoor_seating = "Areas for outdoor gastronomy."
park = "park, outside area for recreation."
picnic_table = "A picnic table"
pitch = "A field for playing football, soccer, cricket, baseball, tennis, etc., a riding arena or a skate park."
playground = "Playground for small children."
resort = "A place used for relaxation or recreation for vacations, tourism possibly with a pool and/or a nearby body of water."
sauna = "A small room or house to experience dry or wet heat sessions, possibly with auxiliary facilities."
slipway = "Boats can be launched here."
sports_centre = "A distinct facility where a range of sports take place."
sports_hall = "A large single room for practising sports indoors."
stadium = "A major sports arena with substantial tiered seating."
summer_camp = "Summer camp is a supervised program for children or teenagers conducted during the summer months."
swimming_area = "A swimming area (river, lake or other water reservoir where swimming is allowed)."
swimming_pool = "A swimming pool."
tanning_salon = "Place where customers can use UV lamps to tan their skin."
track = "A track for running, cycling and other non-motorised racing such as horses, greyhounds."
trampoline_park = "An leisure facility consisting of many interlinked trampolines"
water_park = "An amusement park with features like water slides, recreational pools (e.g. wave pools) or lazy rivers."
wildlife_hide = "A place to observe wildlife."