[office]
accountant = "An office for an accountant."
advertising_agency = "A service-based business dedicated to creating, planning, and handling advertising."
architect = "An office for an architect or group of architects."
association = "An office of a non-profit organisation, society, e.g. student, sport, consumer, automobile, bike association, etc."
chamber = "Seat of a professional chamber, such as bar associations."
charity = "An office of a charitable organization"
company = "An office of a private company."
construction_company = "An office of a construction company."
consulting = "An office for a consulting firm, providing expert professional advice to other companies or organisations."
courier = "A courier delivery service, which is neither a post office or a national post."
coworking = "An office where people can go to work; not limited to a single employer"
diplomatic = "An embassy, diplomatic mission, consulate or liaison office of a foreign government or parastatal entity in a host country."
educational_institution = "An office for an educational institution."
employment_agency = "An office for an employment service."
energy_supplier = "An office for a energy supplier."
engineer = "An office for an engineer or group of engineers."
estate_agent = "A place where you can rent or buy a house."
financial = "An office of a company in the financial sector"
financial_advisor = "A professional who offers financial planning and sells financial services to clients."
forestry = "A forestry office"
foundation = "An office of a foundation"
geodesist = "An office of a person doing land surveys."
government = "An office of a (supra)national, regional or local government agency or department"
graphic_design = "An office of a graphic designer."
guide = "An office of tour guides, mountain guides, hiking guides, dive guides, etc."
harbour_master = "The Harbourmaster's office"
insurance = "An office at which you can take out insurance policies."
it = "An office for an IT specialist."
lawyer = "An office for a lawyer."
logistics = "An office for a forwarder / hauler."
moving_company = "An office which offers a relocation service."
newspaper = "An office of a newspaper"
ngo = "An office for a non-profit, non-governmental organisation (NGO)."
notary = "An office for a notary public (common law)"
politician = "A politician's office."
political_party = "An office of a political party"
property_management = "Office of a property rental company for residential apartments or commercial office space or any other property."
publisher = "An office of a publisher."
quango = "An office of a quasi-autonomous non-governmental organisation."
religion = "An office of a community of faith."
research = "An office for research and development"
security = "An office for private security guards"
surveyor = "An office of a person doing technical surveys, such as land surveys or risk and damage evaluations of properties and equipment."
tax_advisor = "An office for a financial expert specially trained in tax law"
telecommunication = "An office for a telecommunication company"
therapist = "An office of a therapist."
travel_agent = "An office of a travel agent."
tutoring = "An office of tutor or tutoring centre."
union = "An office of a trade union, an association of workers forming a bargaining unit"
university = "An office providing services to university students or staff, or the office of a department / faculty in a university"
visa = "An office of an organisation or business which offers visa assistance."
water_utility = "The office for a water utility company or water board."
yes = "Generic tag for unspecified office type."
administrative = "Using this tag is discouraged, use tag:office=government instead."