[shop.Food_and_beverages_store]
alcohol = "Shop selling alcohol to take away"
bakery = "Shop selling bread"
beverages = "Shop selling alcoholic and non-alcoholic beverages."
brewing_supplies = "Shop selling supplies for brewing of beer, wine and spirits."
butcher = "Shop selling meat"
cheese = "Shop selling cheese."
chocolate = "Shop selling chocolate."
coffee = "Shop selling coffee beans and ground coffee."
confectionery = "Shop selling sweets or candy"
convenience = "A small local shop carrying a small subset of the items you would find in a supermarket"
dairy = "Shop selling dairy products."
deli = "Shop selling delicatessen (fine and gourmet foods), possibly also fine wine."
farm = "Shop or roadside stand selling freshly harvested farm produce"
food = "Shop selling food."
frozen_food = "Shop selling frozen food."
greengrocer = "Shop selling vegetables and fruits."
health_food = "A health food shop; selling wholefoods, vitamins, nutrition supplements and meat and dairy alternatives."
ice_cream = "Shop selling ice cream."
nuts = "Shop selling dried nuts and fruits, edible seeds, etc."
pasta = "Shop selling (fresh) pasta, ravioli, etc."
pastry = "Shop selling baked sweets like cakes, biscuits, strudel and pies."
seafood = "Shop selling fish and seafood."
spices = "Shop selling spices."
tea = "Shop selling tea."
tortilla = "Shop selling tortillas."
water = "Shop selling drinking water."
wine = "Shop selling wine."

[shop.General_store_or_department_store_or_mall]
department_store = "A single large store selling a large variety of goods"
general = "A store that carries a general line of merchandise."
kiosk = "A small shop on the pavement that sells magazines, tobacco, newspapers, sweets and stamps."
mall = "A shopping mall – multiple stores under one roof (also known as a shopping centre)"
supermarket = "Supermarket – a large store with groceries and other items"
wholesale = "Wholesale/warehouse club or cash and carry – a store that sells items in bulk to retailers."

[shop.Clothing_or_shoes_or_accessories_store]
baby_goods = "Shop selling objects for babies (clothes, prams, cots, toys)."
bag = "Shop selling bags."
boutique = "A small shopping outlet, especially one that specializes in elite and fashionable items"
clothes = "Shop selling clothes and/or underwear"
fabric = "Shop selling fabric and other materials for the purpose of making clothes and other products, eg. dress making."
fashion = "Shop selling fashion."
fashion_accessories = "Shop selling fashion accessories."
jewelry = "Jewellers shops."
leather = "Shop selling leather products."
sewing = "A shop that sells sewing supplies (fabric, thread, yarn, knitting needles, sewing machines, etc.)"
shoes = "Shop selling shoes."
shoe_repair = "Shop repairing shoes."
tailor = "A place where clothing is made, repaired, or altered professionally, especially suits and men's clothing"
watches = "Shop selling watches."
wool = "Shop selling wool for making of clothes or other products."

[shop.Discount_store_or_charity]
charity = "A charity shop is a shop operated by a charity, for the purposes of fundraising."
second_hand = "A shop buying and selling used clothes and other things."
variety_store = "A variety store retailer is a retail store that sells inexpensive items."

[shop.Health_and_beauty_shop]
beauty = "A non-hairdresser beauty shop, spa, nail salon, etc.."
chemist = "Shop selling articles of personal hygiene, cosmetics, and household cleaning products"
cosmetics = "Shop selling cosmetics"
erotic = "Shop selling erotic toys, -clothes or other erotic stuff."
hairdresser = "Here you can get your hair cut, coloured, ..."
hairdresser_supply = "A shop, where you can buy hairdressing supplies."
hearing_aids = "Shop selling hearing aids devices"
herbalist = "Shop selling herbs, often for medical purposes."
massage = "A massage shop"
medical_supply = "Shop selling medical supplies."
nutrition_supplements = "Shops that sells one or more nutritional supplements (of vitamins, minerals and/or herbs)"
optician = "Shop selling eyeglasses, contact lenses (may also check your eyes)."
perfumery = "Shop selling perfumery"
tattoo = "A tattoo parlour."

[shop.Do-it-yourself_or_household_or_building_materials_or_gardening_store]
agrarian = "Shop selling agrarian products, like seeds, agricultural machinery, animal feed, etc."
appliance = "Shop selling large electrical items (aka white goods) washing machines, fridges, cookers, ovens, fans, etc."
bathroom_furnishing = "Shop selling bathroom furniture and accessories"
country_store = "Shop selling rural supplies – a range of goods specifically aimed at country dwellers"
doityourself = "Shop selling tools and supplies for do-it-yourself, gardening, ..."
electrical = "Shop selling electrical supplies and devices"
energy = "Shop selling energy"
fireplace = "Shop selling electric fireplaces, stoves or masonry heaters and required fuels"
florist = "Shop selling bouquets of flowers."
garden_centre = "Shop selling potted flowers, maybe even trees."
garden_furniture = "Shop selling garden furniture (sheds, outdoor table furniture, gates, fences, ...)."
gas = "Shop selling technical gas in pressurized containers"
glaziery = "Shop selling and installing glazing for windows and doors."
groundskeeping = "Shop selling outdoor groundskeeping equipment (lawnmowers, chainsaws, small tractors, ...)"
hardware = "Shop selling building supplies including screws, bolts & paints, ..."
houseware = "Shop selling crockery, cutlery, kitchenware and small household appliances."
locksmith = "Shop selling keys."
paint = "Shop selling paints."
pottery = "Shop selling earthenware, stoneware and porcelain and other ceramic ware."
security = "Shop selling security items like burglar alarms, vaults, locking systems, video surveillance cameras, firefighting equipment, alarm systems, warning systems, etc."
tool_hire = "Shop for borrowing tools"
trade = "A place of business that sells to a particular trade or trades, but normally also retails to normal consumers."

[shop.Furniture_and_interior_store]
antiques = "Shop selling antiques."
bed = "Shop selling beds, mattresses and other bedding products."
candles = "Shop selling candles and candle accessories (holders, etc)"
carpet = "Shop selling carpets"
curtain = "Shop selling curtains or drapes."
doors = "Shop selling doors"
flooring = "Shop selling floorings"
furniture = "Shop selling furniture, small decorational items to a whole flat interior"
household_linen = "Shop selling items made of cloth, such as tablecloths, sheets, and pillowcases."
interior_decoration = "Shop selling interior decorations."
kitchen = "A shop where you can plan and buy a kitchen."
lighting = "A shop selling lighting and lamps."
tiles = "Shop selling tiles."
window_blind = "Shop selling window blinds."

[shop.Electronics_store]
computer = "Shop selling computer hardware, peripherals, software, ..."
electronics = "Shop selling consumer electronics (TV, radio,...). Larger ones may also sell computers, fridges, ..."
hifi = "Shop selling High Fidelity or High End environment to listen music or watch films at home"
mobile_phone = "Shop selling mobile phones and accessories"
printer_ink = "A shop that sells or refills printer ink cartridges."
radiotechnics = "Shop selling electronic components, electrical products, radio measuring devices, supplies for radio and electronics."
telecommunication = "Shop selling internet, television or similar services, and related hardware."
vacuum_cleaner = "Shop selling vacuum cleaners and associated products."

[shop.Outdoors_and_sport_or_vehicles_store]
atv = "Shop selling atvs (quads), atv equipment. May also offer rental and repair"
bicycle = "Shop selling bicycles, bicycle equipment. May also offer rental and repair"
boat = "Shop selling boats, boat equipment. May also offer rental and repair"
car = "Car store – a place to buy cars or to get your car repaired"
car_parts = "Shop selling auto parts, auto accessories, motor oil, car chemicals, etc."
car_repair = "Shop repairing cars."
caravan = "A shop for caravans, motorhomes & similar recreational vehicles."
fishing = "Shop selling fishing equipment."
fuel = "Shop selling fuels (motor fuel, wood, coal, gas)."
golf = "Shop selling golf equipment."
hunting = "Shop selling gun and hunting equipment."
military_surplus = "Shop selling used military equipment"
motorcycle = "Shop selling motorcycles and/or related accessories, clothes, parts, and rental services."
motorcycle_repair = "Shop repairing motorcycles."
outdoor = "Shop selling camping, walking, climbing, and other outdoor sports equipment (GPSes, etc.)"
scuba_diving = "Shop selling scuba diving equipment."
ski = "Shop selling skis, ski equipment and may rent or repair them"
snowmobile = "Shop selling snowmobiles, snowmobile equipment and may rent or repair them"
sports = "Shop selling sporting goods."
surf = "Shop selling surfboards, sailboards, wakeboards, and other types of surf style boards. and/or related accessories, clothes, parts, repair and rental services."
swimming_pool = "A store that sells swimming pool equipment and supplies."
trailer = "Shop selling trailers and parts and/or repairing / renting them"
truck = "Shop selling trucks and other commercial vehicles"
tyres = "Shop selling tyres."

[shop.Art_or_music_or_hobbies_store]
art = "Shop which sells works of art. May be paintings, sculpture, or other types of art"
camera = "A shop mainly selling cameras and lenses"
collector = "A shop for different collector's items like stamps, coins, action figures, etc."
craft = "An arts and crafts supply store. Commonly sold items are paper, canvas, paint, pencils, crafting wood, crafting tools, etc."
frame = "Shop selling frames."
games = "Shop selling board games, card games and/or role-playing games."
model = "Shop specialising in the sale of scale models."
music = "Shop selling recorded music (vinyl/CDs/...)"
musical_instrument = "Shop selling musical instruments, lyrics, scores."
photo = "Shop selling products or services related with photography."
trophy = "Store selling trophies, awards, plaques etc."
video = "Shop selling or renting out videos/DVDs."
video_games = "Shop selling video games."

[shop.Stationery_or_gifts_or_books_or_newspapers_store]
anime = "Shop selling anime stuff."
books = "Shop selling books"
gift = "Shop selling gifts, greeting cards, or tourist gifts (souvenirs)"
lottery = "A shop of which the main or only purpose is the sale of lottery tickets."
newsagent = "Shop selling newspapers, cigarettes, other goods"
stationery = "Shop selling office supplies"
ticket = "Shop selling tickets for concerts, events, public transport, …"

[shop.other]
bookmaker = "A shop that takes bets on sporting and other events at agreed upon odds."
cannabis = "A shop primarily and legally selling non-medical cannabis products"
copyshop = "Shop selling photocopying and printing services."
dry_cleaning = "Shop or kiosk offering a clothes dry cleaning service."
e-cigarette = "Shop selling electronic cigarettes."
funeral_directors = "Providing services related to funeral arrangements, may also be known as a 'funeral parlour' or 'undertakers'."
laundry = "A shop to get your normal clothes washed."
money_lender = "A money lender offers small personal loans at high rates of interest."
outpost = "Shop primarily used to pick-up items ordered online."
party = "A shop for party and festival supplies, like costumes, etc."
pawnbroker = "A pawnbroker (or pawnshop) is an individual or business that offers secured loans to people. See also shop=second_hand"
pest_control = "Shop selling pest control goods to exterminate rats, insects etc."
pet = "A shop for pets, animals and toys or food for them."
pet_grooming = "A shop offering grooming services for pets (most frequently dogs)"
pyrotechnics = "Store of pyrotechnics: fireworks, firecrackers, sparklers etc."
religion = "Shop selling religious articles, church shop. See also religion=*"
rental = "Shop that rents different kinds of vehicles or (sport) equipment"
storage_rental = "Service offering storage"
tobacco = "Shop selling tobacco, cigarettes and their related accessories."
toys = "Shop selling toys."
travel_agency = "Shop selling tickets for travelling. Also known as a tour operator."
vacant = "An unused vacant shop."
weapons = "Shop focused on selling weapons like knives, guns etc."
yes = "A shop"
