[sport]
9pin = "Nine-pin bowling is a bowling game played primarily in Europe with only nine pins."
10pin = "Ten-pin bowling is a sport in which a player, or 'bowler' rolls a bowling ball down a lane with the objective of scoring points by knocking down as many pins as possible. In Canada, the United States, United Kingdom and Australia, the game is commonly referred to as just 'Bowling'."
aerobics = "Aerobics"
american_football =  "American football is a sport played by two teams of eleven players on a rectangular field with goalposts at each end."
aikido = "Aikido is a Japanese martial art by blending with the motion of the attacker and redirecting the force of the attack rather than opposing it head-on."
archery = "Archery is the art, practice, or skill of propelling arrows with the use of a bow."
athletics = "Track and field athletics is a collection of sports which combines various athletic contests based on the skills of running, jumping, and throwing. Track and field is often categorised under the umbrella sport of athletics, which also includes road running, cross country running, and race walking."
australian_football = "Australian rules football, officially known as Australian football, also called football, footy, Aussie rules, or AFL is a sport played between two teams of eighteen players on the field of either an Australian football ground, a modified cricket field, or a similarly sized sports venue."
badminton = "Badminton is a racquet sport played by singles or in teams of two, who take positions on opposite halves of a rectangular court (pitch) divided by a net. Players score points by striking a shuttlecock with their racquet so that it passes over the net."
bandy = "Bandy is a team winter sport played on ice, in which skaters use sticks to direct a ball into the opposing team's goal. The sport has common background with association football, ice hockey and field hockey. The bandy field is about the same size as a football pitch. It is played on ice like ice hockey."
base = "BASE jumping, is an activity that employs an initially packed parachute to jump from fixed objects. 'B.A.S.E.' is an acronym that stands for four categories of fixed objects: buildings, antennas, spans, and earth. A more down to earth approach to parachuting."
baseball = "Baseball is a bat-and-ball game played between two teams of nine players on a field (pitch or stadium) each who take turns batting and fielding."
basketball = "Basketball is a sport played by two teams of five players on a rectangular court. Played indoors or outdoors"
beachvolleyball = "Beach volleyball is a team sport played by two teams of two players on a sand court divided by a net."
biathlon = "The biathlon is a winter sport that combines cross-country skiing and rifle shooting."
billiards = "Cue sports, also known as billiard sports, are a wide variety of games of skill generally played with a cue stick which is used to strike billiard balls, moving them around a cloth-covered billiards table bounded by rubber cushions."
bmx = "BMX or Bicycle motocross is a cycle sport performed on BMX bikes, either in competitive BMX racing or freestyle BMX, or else in general on- or off-road recreation."
bobsleigh = "Bobsleigh, Luge, or Bobslede is a winter sport in which teams of two or four make timed runs down narrow, twisting, banked, iced tracks in a gravity-powered sled."
boules = "Boules (Pétanque, lyonnaise, bocce, and bocce volo) is a group of games in which the objective is to throw or roll heavy balls as close as possible to a small target ball."
bowls = "Bowls or lawn bowls is a sport in which the objective is to roll biased balls so that they stop close to a smaller ball called a 'jack' or 'kitty'. It is played on a pitch which may be flat (for 'flat-green bowls') or convex or uneven (for 'crown-green bowls'). It is normally played outdoors (although there are many indoor venues) and the outdoor surface is either natural grass, artificial turf, or cotula (in New Zealand)."
boxing = "Boxing (pugilism, prize fighting, the sweet science or in Greek pygmachia) is a combat sport played in a boxing ring in which two people engage in a contest of strength, speed, reflexes, endurance, and will, by throwing punches with gloved hands against each other."
bullfighting = "Bullfighting, both on foot and on horseback, is a physical contest in which bulls are fought by humans."
canadian_football = "Canadian football (CFL) is a form of gridiron football played in Canada in which two teams of 12 players each compete for territorial control of a field of play called a pitch. In Canada, the term football may refer to Canadian football and American football collectively, or either sport specifically, depending on context."
canoe = "Canoe and Kayak are a narrow human-powered boats, primarily designed to be manually propelled by means of a paddle for the use of racing, whitewater canoeing, touring and camping, freestyle, and general recreation. The intended use of the canoe dictates its hull shape and construction material."
chess = "Chess is a two-player strategy board game played on a chessboard."
cliff_diving = "Non-competitive diving is jumping from a cliff or a rock into water. Such non-competitive diving can occur indoors and outdoors. Outdoor diving typically takes place from cliffs or other rock formations either into fresh or salt water. However, man-made diving platforms are sometimes constructed in popular swimming destinations. Outdoor diving requires knowledge of the water depth and currents as conditions can be dangerous."
climbing = "Rock climbing marks elements to represent natural climbing sites (climbing areas, sectors, crags, halls, frozen waterfalls, etc.) or artificial climbs (Climbing walls, Indoor climbing, etc.)."
climbing_adventure = "Climbing Adventure often called 'Adventure Park', 'Ropes Courses', 'Climbing Adventure', 'Zip-line', or 'Treetop Adventure', can be used for the recreational sport when people get mountain hiking accessories and try to climb, walk or otherwise move on prebuilt wires and other objects high above on the trees using continuous safety measures. These are usually open for everyone including kids and do not require special abilities apart from good physical condition."
cockfighting = "Cockfighting is a common spectator sport in many countries between two roosters (cocks), held in a ring called a cockpit."
cricket = "Cricket is a bat-and-ball sport contested by two teams, usually of eleven players, each on a large grass Cricket pitch. Played on a large circular or oval-shaped grassy Cricket field ground."
crossfit = "CrossFit, a branded fitness regimen"
croquet = "Croquet is a sport or game that is played between two or more players embedded on a small grass playing court or pitch which involves hitting plastic or wooden balls with a mallet through hoops (often called 'wickets' in the United States)."
curling = "Curling is a sport in which players slide stones on a sheet of ice towards a target area which is segmented into four concentric rings. It is related to bowls, boules and shuffleboard. Indicating that curling is the sport the facility is intended for."
cycle_polo = "A cycle polo"
cycling = "Cycling, also called bicycling, Mountain biking or biking, is the use of bicycles for transport, recreation, or for sport."
dance = "Generic dance sport."
darts = "Darts is a form of throwing game in which small missiles are thrown at a circular target (dartboard) fixed to a wall."
dog_agility = "Dog agility is a dog sport in which a handler directs a dog through an obstacle course in a race for both time and accuracy."
dog_racing = "Greyhound racing being the most common type of this sport. There are other sports that involves dog racing, such as Dogsled, Dachshund, Dog scootering, Lure coursing, and Skijoring racing."
dragon_boat = "Ancient Chinese boat"
equestrian = "Equestrianism / [W]equestrian sport is a sport that is practised with the horse as a partner. Often associated internationally with show jumping and dressage, but also including other disciplines like eventing, endurance riding, horseball, reining, tent pegging, vaulting, polo, driving, rodeo and more (see [W] List of equestrian sports)."
fencing = "Fencing is the martial art of fighting with blades. The most common version of fencing today, also called olympic fencing or competitive fencing, is divided into three weapon categories: foil, sabre (spelled saber in the United States) and épée. Classical fencing uses the same three weapons, but approaches fencing as a martial art."
field_hockey = "Field hockey is a team sport of the hockey family. Players use sticks made out of wood or fiber glass to hit a round, hard, rubber like ball. The game can be played on a grass field or a turf field as well as an indoor board surface."
fitness = "To develop physical fitness"
five-a-side = "A variation of soccer with only 5 persons per team on a smaller pitch"
floorball = "Floorball is a type of floor hockey with five players and a goalkeeper in each team."
four_square = "A hand ball game played on a square court."
free_flying = "Hang gliding and/or Paragliding that is a foot launched aircraft, without motorisation. Paragliding/Hanggliding/... takeoff, landings, towing, etc. and related amenities and properties"
futsal = "Futsal is a sport played by two teams of five players on a rectangular court."
gaelic_games = "Gaelic games such as Hurling, Gaelic Football, Camogie, predominantly played in Ireland."
gaga = "Gaga (or gaga ball) is a variant of dodgeball that is played in a gaga 'pit'"
golf = "Golf for golf courses"
gymnastics = "Gymnastics"
handball = "Handball"
hapkido = "Hapkido is a dynamic and highly eclectic Korean martial art. It is a form of self-defense that employs joint locks, grappling and throwing techniques of other martial arts, as well as kicks, punches, and other striking attacks."
hiking = "Going for a long, vigorous walk, usually on trails or footpaths in the countryside."
hockey = "Hockey"
horseshoes = "Horseshoes"
horse_racing = "Horse racing is an equestrian sport in which several horses simultaneously race against each other."
ice_hockey = "Ice Hockey is a team sport played on ice in which two teams of skaters use sticks to shoot a hard rubber hockey puck into their opponent's net to score points."
ice_skating = "Ice skating is a sport or pastime by moving on ice while using ice skates."
ice_stock = "Ice stock sport, also known as Bavarian Curling, is a winter sport, somewhat similar to Curling."
judo = "Judo"
karate = "Karate."
karting = "Kart racing."
kickboxing = "Kickboxing is a group of stand-up combat sports based on kicking and punching."
kitesurfing = "Kitesurfing"
korfball = "Korfball"
krachtbal = "Team sport played with a heavy ball on a rectangular pitch, originating in West-Flanders, Belgium"
lacrosse = "A team sport played with a lacrosse stick and a lacrosse ball. Players use the head of the lacrosse stick to carry pass, catch, and shoot the ball into the goal."
laser_tag = "Laser tag is a tag game played in an arena."
martial_arts = "Martial arts are codified systems and traditions of combat"
miniature_golf = "Miniature golf, also known as minigolf, mini-putt, crazy golf, or putt-putt, is an offshoot of the sport of golf focusing solely on the putting aspect of its parent game."
model_aerodrome = "Radio-controlled aircraft"
motocross = "Motocross is a form of motorcycle racing held on enclosed off-road circuits."
motor = "Motorsport."
multi = "different kinds of sport."
netball = "Netball is a sport played by two teams on a rectangular court."
obstacle_course = "Obstacle course. A series of challenging physical obstacles an individual or team must navigate usually while being timed."
orienteering = "Orienteering. Navigation sport with Map and compass."
paddle_tennis = "Paddle tennis"
padel = "A racket sport played in pairs. It consists of bouncing the ball in the opponent's court, with the possibility of bouncing it off the walls."
paintball = "A game in which players mark their opponents with colored paint capsules shot out of an air gun."
parachuting = "Parachuting or skydiving take-off or landing site"
paragliding = "Paragliding. Paragliding take-off or landing site"
parkour = "Parkour is a training discipline using movement that developed from military obstacle course training."
pelota = "Pelota. Spanish Group name for a number of ball games (Baseball, Basque pelota, Bocce, Jai alai, Valencian pilota)."
pesapallo = "Pesäpallo, sometimes known as Finnish baseball, is a fast-moving bat-and-ball sport where the offense tries to score by hitting the ball successfully and running through the bases, while the defense tries to put the batter and runners out."
pickleball = "Pickleball, a tennis-like game played with a slower ball on a smaller court."
pilates = "Pilates is a physical fitness system developed in the early 20th century by Joseph Pilates."
pole_dance = "Pole dance as kind of sport"
racquet = "Racquetball. Group name of sports that are played with a racquet"
rc_car = "Radio-controlled car"
roller_skating = "Roller skating is a sport or recreational activity by travelling on surfaces with roller skates."
rowing = "Rowing"
rugby_league = "Rugby league. One of the two codes of rugby football, split from rugby union in 1895, along with subsequent rule changes"
rugby_union = "Rugby union. Rugby union is a full contact team sport, a form of football which originated in England in the early 19th century."
running = "Running"
safety_training = "Safety Training. To ensure that people are aware of their surrounding hazards and can respond appropriately in an emergency."
sailing = "Sailing"
scuba_diving = "Scuba diving"
shooting = "Shooting sport"
shot-put = "Shot-put is a sport involving throwing a heavy spherical object as far as possible."
skateboard = "Skateboard"
ski_jumping = "Ski jumping is a winter sport in which competitors aim to achieve the longest jump after descending from a specially designed ramp on their skis."
skiing = "Skiing."
snooker = "Snooker is a cue sport that is played on a rectangular table covered with a green cloth with pockets at each of the four corners and in the middle of each long side."
soccer = "Soccer. Association football, more commonly known as football or soccer, a team sport played between two teams of eleven players."
softball = "A bat-and-ball game similar to baseball."
speedway = "Motorcycle speedway, usually referred to as speedway, is a motorcycle sport involving four and sometimes up to six riders competing over four anti-clockwise laps of an oval circuit."
squash = "Squash is a racket and ball sport played by two or four players in a four-walled court with a small, hollow rubber ball."
sumo = "Sumo. A traditional martial arts of Japan."
surfing = "Surfing"
swimming = "Swimming"
table_tennis = "Table tennis"
table_soccer = "Table Soccer or Table Football, also known as Foosball, Fussball, Kicker, or Tecball, is a table-top game and sport based off association football (soccer)."
taekwondo = "Taekwondo"
tennis = "Tennis"
teqball = "Place for playing teqball."
toboggan = "Toboggan. public sledding run"
trampoline = "Trampoline sport is a sport that is carried on large trampolines indoor or outdoors"
ultimate = "Ultimate, also known as ultimate frisbee, is a team sport played with a flying disc (frisbee)."
ultralight_aviation = "Ultralight aviation"
volleyball = "Volleyball"
wakeboarding = "Wakeboarding is a water sport in which the rider, standing on a wakeboard, is towed behind a motorboat in order to perform aerial maneuvers."
water_polo = "Water polo."
water_ski = "Waterskiing either on a cable ski course, or pulled by a boat."
weightlifting = "Olympic weightlifting"
windsurfing = "Wind powered board on water."
wrestling = "Wrestling"
yoga = "Yoga"
zurkhaneh_sport = "A traditional system of athletics."